nav:
  Home: /
#  About: /about/
  Blog: /archives/
  Tags: /tags/
#  Projects:

# projects_url:

customize:
    gravatar:
        email:
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon:
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/logo.jpg
        gravatar: false
      android:
        url: /images/logo.jpg
        gravator: false
      apple:
        url: /images/logo.jpg
        gravator: false

    show_all_posts: false
    post_count: 5
    highlight: rainbow

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics:

# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
